CREATE DATABASE DuckDB_SAMPLE
GO
CREATE DATABASE Aviation_SAMPLE
GO
CREATE DATABASE Person_SAMPLE
GO
CREATE DATABASE AdventureworksDW_SAMPLE
GO
CREATE DATABASE FEDERATION
GO
CREATE DATABASE DataType_SAMPLE
GO